### ISSUE TITLE
Music will not play for numbers game on iPhone

### ISSUE THREAD

**Issue by Hoppenstein** [ashleypancho/countdown-app#24]
For reasons ash seems to be aware of, the music will not play for the numbers game, but will for the other two games.

**Comment by ashleypancho** [comment]
Seeing this console error when playing Numbers game on iOS only: 
> NotAllowedError: The play method is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.

Possible cause is that numbers game triggers music after displaying tiles, whereas the letters game and conundrum is triggered on/after a button press. 

More information for solutions: https://stackoverflow.com/questions/57504122/browser-denying-javascript-play
